name: CI

on: 
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

permissions:
  contents: read
  id-token: write 

jobs: 
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Configure AWS Credentials (OIDC)
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::034866042287:oidc-provider/token.actions.githubusercontent.com
          aws-region: us-east-1

      - name: Login to Amazon ECR
        if: github.event_name == 'push'
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build and push image
        if: github.event_name == 'push'
        env: 
          REGISTRY: 034866042287.dkr.ecr.us-east-1.amazonaws.com
          SHA: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/notes-api:$SHA -t $REGISTRY/notes-api:latest .
          docker push $REGISTRY/notes-api:$SHA
          docker push $REGISTRY/notes-api:latest
